### PR TITLE
i fixed ur dogshit tier project

### PR DESCRIPTION
**Pull request by environment-dev**
yes

### CODE REVIEW

**Comment by DomeQdev** [comment]
no, this code is painful. Do not push it

**Comment by environment-dev** [comment]
> no, this code is painful. Do not push it
ur painful

**Comment by DomeQdev** [comment]
> > no, this code is painful. Do not push it
> 
> ur painful

your father is painful (fr
)

**Comment by DomeQdev** [comment]
> > > no, this code is painful. Do not push it
> > 
> > 
> > ur cumming
> 
> your father is painful (fr)

+ you didn't added gpg key to last commit, it won't be accepted to such a big repo like Cattoistaken/Basic-Express-Server.

**Comment by environment-dev** [comment]
> > > > no, this code is painful. Do not push it
> > > 
> > > 
> > > ur painful
> > 
> > 
> > your father is painful (fr)

childish

> * you didn't added gpg key to last commit, it won't be accepted to such a big repo like Cattoistaken/Basic-Express-Server.
wow! i do NOT give a fuck.

**Comment by Nekoyre** [comment]
oh yeah server.js bad name index.js ezpz

**Comment by environment-dev** [comment]
> oh yeah server.js bad name index.js ezpz

done

**Comment by Cattoistaken** [comment]
ty

**Comment by Cattoistaken** [comment]
idk why u even bothered

**Comment by Cattoistaken** [comment]
> no, this code is painful. Do not push it

your painful

**Pull request merged**
